llm_config:
    llm: 4o-mini
    oai_key: "sk-YOURKEY"
    fw_key: "fw_YOURKEY"
    gemini_key: "g_YOURKEY"
    deepseek_key: "ds_YOURKEY"
    xai_key: "x_YOURKEY"

task_config:
    task: classification
    random_seed: 42
    data_name: one_subject_negative_part_1
    save_results: True
